#define CC_E    (FLAG_VAL(ZF))
#define CC_NE   (FLAG_VAL(ZF) == 0)
#define CC_JB   (FLAG_VAL(CF)==1)
#define CC_JBE  (FLAG_VAL(CF) || FLAG_VAL(ZF))
#define CC_CXZ  (reg_w(R_CX)==0)
#define CC_ECXZ (reg_l(R_ECX)==0)
#define CC_L    (FLAG_VAL(OF) != FLAG_VAL(SF))
#define CC_LE   ((FLAG_VAL(OF) != FLAG_VAL(SF)) || FLAG_VAL(ZF))
#define CC_G    ((!FLAG_VAL(ZF))&&(FLAG_VAL(SF)==FLAG_VAL(OF)))
#define CC_GE   (FLAG_VAL(OF)==FLAG_VAL(SF))
#define CC_A    ((FLAG_VAL(CF) == 0) && (FLAG_VAL(ZF) == 0))
#define CC_AE   (FLAG_VAL(CF) == 0)
#define CC_NA   (FLAG_VAL(CF) || FLAG_VAL(ZF))
#define CC_NAE  (FLAG_VAL(CF))
#define CC_NB   (FLAG_VAL(CF==0))
#define CC_NBE  ((FLAG_VAL(CF)==0)&&(FLAG_VAL(ZF)==0))
#define CC_NG   (jng, FLAG_VAL(ZF) || (FLAG_VAL(SF) != FLAG_VAL(OF)))
#define CC_NGE  (jnge, FLAG_VAL(SF) != FLAG_VAL(OF))
#define CC_JNL  (FLAG_VAL(SF)==FLAG_VAL(OF))
#define CC_JNEL ((FLAG_VAL(SF)==FLAG_VAL(OF)) && (FLAG_VAL(ZF)==0))
#define CC_JNO  (!FLAG_VAL(OF))
#define CC_JNP  (!FLAG_VAL(PF))
#define CC_JNS  (!FLAG_VAL(SF))
#define CC_JNZ  (!FLAG_VAL(ZF))
#define CC_JO   (FLAG_VAL(OF))
#define CC_JP   (FLAG_VAL(PF))
#define CC_JS   (FLAG_VAL(SF))

#undef OFFSET
#include "exec/template-end.h"
